import SwiftUI
import Foundation
import UIKit

struct AboutView: View {
    private let websiteURL = URL(string: "https://xbalsoftware.github.io/eyebrary/")!
    private let privacyURL = URL(string: "https://xbalsoftware.github.io/eyebrary/#privacy")!
    private let supportURL = URL(string: "https://xbalsoftware.github.io/eyebrary/#support")!

    private var appVersionText: String {
        let version = Bundle.main.object(forInfoDictionaryKey: "CFBundleShortVersionString") as? String
        let build = Bundle.main.object(forInfoDictionaryKey: "CFBundleVersion") as? String

        switch (version, build) {
        case let (v?, b?) where !v.isEmpty && !b.isEmpty:
            return "Version \(v) (\(b))"
        case let (v?, _ ) where !v.isEmpty:
            return "Version \(v)"
        default:
            return "Version unavailable"
        }
    }

    private let descriptionText = "EYEbrary is a clinical documentation and patient-education tool designed for eye-care professionals. It allows clinicians to create customizable library entries and generate professional patient summary reports following an eye examination."

    private let medicalDisclaimerText = """
This application is intended for use by licensed eye-care professionals as a documentation and patient-education aid.

The application does not provide medical advice, diagnosis, or treatment recommendations. All clinical information, assessments, and plans generated using this software are entered and reviewed by the clinician using the application.

The developer does not verify the accuracy or completeness of the information entered by users. Clinicians are solely responsible for ensuring that all clinical information is correct and appropriate before sharing it with patients or including it in the medical record.

This software is provided as a formatting and document-generation tool only. It should not be relied upon as a substitute for professional judgment, clinical training, or established standards of care.

Some versions of the application may include example or pre-installed library entries intended as starting points for documentation or patient education. These entries are provided for convenience only and may not be complete, current, or appropriate for any specific patient or clinical situation. Clinicians must review and modify all content before using it in patient communications or medical documentation.
"""

    private let licenseText = "This software is provided as-is without warranty of any kind. The developer shall not be liable for any damages arising from the use of this application or from clinical decisions made using documents generated by the application."

    private func openURL(_ url: URL) {
        UIApplication.shared.open(url)
    }

    var body: some View {
        List {
            Section {
                VStack(alignment: .leading, spacing: 6) {
                    Text("EYEbrary")
                        .font(.headline)

                    Text(descriptionText)
                        .font(.subheadline)
                        .foregroundStyle(.secondary)
                        .fixedSize(horizontal: false, vertical: true)
                        .padding(.top, 2)
                }
                .padding(.vertical, 4)
            }

            Section("App Information") {
                LabeledContent("Version") {
                    Text(appVersionText)
                        .foregroundStyle(.secondary)
                }

                LabeledContent("Developer") {
                    Text("Xbal Software")
                        .foregroundStyle(.secondary)
                }
            }

            Section("Legal") {
                VStack(alignment: .leading, spacing: 12) {
                    Text(medicalDisclaimerText)
                        .font(.body)
                        .fixedSize(horizontal: false, vertical: true)
                }
                .padding(.vertical, 4)

                Button {
                    openURL(privacyURL)
                } label: {
                    HStack {
                        Text("Privacy Policy")
                        Spacer()
                        Image(systemName: "arrow.up.right.square")
                            .foregroundStyle(.tertiary)
                    }
                }
                .buttonStyle(.plain)

                VStack(alignment: .leading, spacing: 12) {
                    Text(licenseText)
                        .font(.body)
                        .fixedSize(horizontal: false, vertical: true)
                }
                .padding(.vertical, 4)
            }

            Section("Support") {
                Button {
                    openURL(websiteURL)
                } label: {
                    HStack {
                        Text("Website")
                        Spacer()
                        Image(systemName: "arrow.up.right.square")
                            .foregroundStyle(.tertiary)
                    }
                }
                .buttonStyle(.plain)

                Button {
                    openURL(URL(string: "https://xbalsoftware.github.io/eyebrary/user-manual.html")!)
                } label: {
                    HStack {
                        Text("Full User Manual")
                        Spacer()
                        Image(systemName: "arrow.up.right.square")
                            .foregroundStyle(.tertiary)
                    }
                }
                .buttonStyle(.plain)

                Link(destination: URL(string: "mailto:xbalsoftware@gmail.com")!) {
                    HStack {
                        Text("Email")
                        Spacer()
                        Text("xbalsoftware@gmail.com")
                            .foregroundStyle(.secondary)
                    }
                }
                .buttonStyle(.plain)
            }
        }
        .navigationTitle("About")
        .navigationBarTitleDisplayMode(.inline)
    }
}
